version: 2
services:
  backend:
    name: taoyuan-waste-backend
    build:
      dockerfile: backend/Dockerfile
      context: .
    deploy:
      replicas: 1
      restartPolicy: always
    healthcheck:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - PORT=8000
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi  
        cpu: 500m